### ISSUE TITLE
After integrate cast framework app crashes when opening.

### ISSUE THREAD

**Issue by Karthikg206** [googlecast/CastVideos-android-v2#45]
After integrate cast framework app crashes when opening.when google it everyone  says device must update their google play services. How to prevent those errors.

Log says:
java.lang.RuntimeException: com.google.android.gms.dynamite.DynamiteModule$zza: No acceptable module found. Local version is 0 and remote version is 0

**Comment by naddaf** [comment]
You're running old version of play services; update that on your device.

**Comment by Karthikg206** [comment]
Not on my device it is live version.How to restrict users who don't have updated Google play services??
