### ISSUE TITLE
Chromecast integration crashes initially when app open.In live version how to restrict users who don't have updated google play services? 

### ISSUE THREAD

**Issue by Karthikg206** [googlecast/CastVideos-android-v2#46]
After integrate cast framework app crashes when opening.when google it everyone says device must update their google play services. How to prevent those errors.

Log says:
java.lang.RuntimeException: com.google.android.gms.dynamite.DynamiteModule$zza: No acceptable module found. Local version is 0 and remote version is 0

**Comment by naddaf** [comment]
Check the version of play services and stop or warn the user before moving forward. This is not related to the CCL or CastVideos-app, you should do that in your own app and is the app's responsibility.
